### ISSUE TITLE
Exception message not working in Toastr

### ISSUE THREAD

**Issue by Slayvin** [sugeng-sulistiyawan/yii2-toastr#4]
### What steps will reproduce the problem?
Add a new Flash message wich has a multiline string (with "\n" for example).
Such message can be generated by a thrown exception.

### What is the expected result?
The flash message is displayed

### What do you get instead?
The flash message is not displayed, and the javascript console has an error : _Uncaught SyntaxError: Invalid or unexpected token_

The workaround is to replace 'new line' character with a valid html character:
```php 
$text = str_replace(array("\r\n", "\r", "\n"), '<br />', $exception->getMessage());
Yii::$app->session->setFlash('error', $text );
```

**Comment by sugeng-sulistiyawan** [comment]
Can you include the complete source code along with the screenshots, because we checked it didn't seem to have a problem. Thanks
